# Generated by Django 6.1.1 on 2026-09-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('date', models.CharField(help_text='e.g. Sep 2026', max_length=50)),
                ('link', models.URLField()),
                ('tags', models.CharField(help_text='Comma-separated tags (e.g. AI, Career)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Lower number shows up first')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
