# Generated by Django 6.1.1 on 2026-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('🎤 Speaker', 'Speaker'), ('💻 Hackathon', 'Hackathon'), ('🎟️ Conference', 'Conference'), ('🤝 Meetup', 'Meetup'), ('🛠️ Workshop', 'Workshop'), ('👀 Attendee', 'Attendee')], default='🤝 Meetup', max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_images/')),
                ('link', models.URLField(blank=True, help_text='Link to LinkedIn post, GitHub, or event page', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Meetup',
        ),
    ]
