# Generated by Django 6.1.1 on 2026-09-29 16:59

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_communityevent_delete_meetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '400x220', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='community_images/'),
        ),
    ]
