# Generated by Django 6.1.1 on 2026-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_communityevent_cropping_alter_communityevent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('date_issued', models.CharField(help_text='e.g. Sep 2026', max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
