# Generated by Django 6.1.1 on 2026-09-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, help_text='Details about the certification', null=True),
        ),
    ]
