# Generated by Django 6.1.1 on 2026-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certification_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='type',
            field=models.CharField(choices=[('Award', 'Award'), ('Certification', 'Certification')], default='Certification', max_length=50),
        ),
    ]
