# Generated by Django 6.1.1 on 2026-09-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_certification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='PROJECT', help_text='e.g. AI · RAG', max_length=100),
        ),
    ]
